language: python
python:
    - "3.5"
    - "3.6"

before_install:
    - "pip install pytest"
    - "pip install coveralls"

install:
    - "pip install -r requirements.txt"
    - "pip install ."
script:
    - "coverage run --source stylo setup.py test"
    - "coverage report"
    - "cd docs && make doctest && cd .."

after_success:
    - "coveralls"
