language: python
matrix:
  include:
    - env: "TOXENV=py35"
      python: "3.5"

    - env: "TOXENV=py36"
      python: "3.6"

    - env: "TOXENV=lint"
      python: "3.6"

    - env: "TOXENV=docs"
      python: "3.6"

    - env: "TOXENV=py37"
      python: "3.7"
      sudo: required
      dist: xenial

before_install:
    - "pip install tox coveralls"

script:
    - "tox -v"

after_success:
    - if [ "$TOXENV" == "py36" ]; then coveralls; fi
