language: python
matrix:
  include:
    - env: "TOXENV=py35"
      python: "3.5"

    - env: "TOXENV=py36"
      python: "3.6"

    - env: "TOXENV=py37"
      python: "3.7"
      sudo: required
      dist: xenial

    - env: "TOXENV=lint"
      python: "3.6"

    - env: "TOXENV=benchmark"
      python: "3.6"

    - env: "TOXENV=docs-check"
      python: "3.6"

    - env: "TOXENV=docs-build"
      python: "3.6"

before_install:
    - "pip install tox coveralls"

script:
    - "tox -v"

after_success:
    - if [ "$TOXENV" == "py36" ]; then coveralls; fi

deploy:
    - provider: pages
      skip-cleanup: true
      github-token: $GH_TOKEN
      local-dir: "docs/_build/html/"
      verbose: true
      on:
        branch: develop
        condition: $TOXENV = docs-build
        python: 3.6
